NO REVIEWS : Framebuffer structure
Wandalen/cgtools pull request #21
Opened 2024-11-12 19:00 UTC by FairlyBet

So, this is another iteration of me trying to write some framebuffer structure.

# Motivation

There are 2 cases that i wanted to improve

1. Simplifying binding a framebuffer with multiple draw buffers.
When you want to draw into a framebuffer with several color attachments 
you need to call `gl.draw_buffers` with an array that contains `GL::COLOR_ATTACHMENT#` values
for each draw buffer you want to draw into. 
For example, if you have a framebuffer with ColorAttachment0 and ColorAttachment2, to draw into these
attachments you need to specify an array `[ GL::COLOR_ATTACHMENT0, GL::NONE, GL::COLOR_ATTACHMENT2 ]`
into `gl.draw_buffers`. Besides this, the array has to be converted into `js_sys::Array` and all of this is quite annoying.
2. Storing attachments and framebuffer in one place.
Typically when you have a framebuffer and, for instance, a texture attached to it, you may want to have them in one place.

# Implementation

## What it does

There is `Framebuffer` struct that encapsulates `WebGlFramebuffer` object. Its API exposes functions for attaching textures and renderbuffers, functions for binding framebuffer for drawing and for reading. It keeps track of color attachments so it can properly bind draw buffers when you bind framebuffer for drawing. There are `bind_all_drawbuffers`, it binds all color attachment for drawing, and `bind_drawbuffers` in which you can specify attachments you want to draw into, and, if framebuffer doesn't actually have some of attachments you specified, it will return errror. Also you can specify empty color attachments when you want no color output.

## Trade-offs

There is a thing that is really not great. Since WebGl is global state, you can modify framebuffer bypassing the API.

``` rust
let framebuffer = Framebuffer::new().unwrap();
framebuffer.bind_all_drawbuffers( &gl );
// At this point framebuffer is bound as GL::DRAW_FRAMEBUFFER
// So you can easily modify it with WebGl functions bypassing API
gl.framebuffer_texture_2d( GL::DRAW_FRAMEBUFFER, GL::COLOR_ATTACHMENT1, GL::TEXTURE_2D, texture.as_ref(), 0 );
```

Doing so will invalidate framebuffer's inner color attachment tracking data. And there's nothing to do about it :(

# Conclusion

I need some feed back on all of this, cause I really can't say is it worth implementing such a struct or maybe just do a single  function that will improve annoying `gl.draw_buffers` and don't bother. Also there is a `PreserveFramebuffer` struct which exposes same API as `Framebuffer` but also stores attachments inside a hashmap so this is implementation of the second point from motivation section.

2024-11-13 12:51 UTC, JekiXD commented on module/min/minwebgl/src/framebuffer.rs
> +      }
You can also do map_err

2024-11-13 12:51 UTC, JekiXD commented on module/min/minwebgl/src/framebuffer.rs
> +  }
Maybe would be more clean to do From< AttachmentType > for u32

2024-11-21 09:28 UTC, projdysvit requested changes

2024-11-21 09:28 UTC, quisego commented on module/min/minwebgl/src/framebuffer.rs
> +  }
It might be better to implement From trait?

2024-11-21 09:28 UTC, projdysvit commented on module/min/minwebgl/src/color_attachments.rs
> +    pub fn from_slice( attachments : &[ ColorAttachment ] ) -> Self
You are not checking the length of the input slice, this can cause an overflow.

2024-11-21 09:28 UTC, projdysvit commented on module/min/minwebgl/src/color_attachments.rs
> +      for attachment in attachments
```suggestion
      for &attachment in attachments.iter().take(MAX_COLOR_ATTACHMENTS)
```

2024-11-22 14:22 UTC, projdysvit approved these changes
Good job👍

2025-03-27 11:55 UTC, merged